name = "ASEAtomsIO"
uuid = "d58a7de9-158d-43a8-b997-753c0d092fa5"
authors = ["Rashid Rafeek <rashidrafeek@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
